---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script:
  - 'bundle exec rake $CHECK'
matrix:
  include:
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 4.0" CHECK=test
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 4.0" CHECK=rubocop
  - rvm: 2.2.5
    env: PUPPET_GEM_VERSION="~> 4.0" CHECK=test
  - rvm: 2.2.5
    env: PUPPET_GEM_VERSION="~> 4.0" CHECK=rubocop
