---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.0.0
  - 2.1.0
script:
  - 'bundle exec rake $CHECK'
matrix:
  include:
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 4.0" CHECK=test
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 4.0" CHECK=rubocop
