---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script:
  - 'bundle exec rake $CHECK'
env:
  - PUPPET_GEM_VERSION="~> 3.4.0" CHECK=test
  - PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES=yes CHECK=test
  - PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=yes CHECK=test
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes CHECK=test
  - PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes CHECK=test
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes CHECK=test
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes CHECK=test
matrix:
  exclude:
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.4.0" CHECK=test
  include:
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 4.0" CHECK=test
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 4.0" CHECK=rubocop
